### ISSUE TITLE
Hata Mesajları İçin Çoklu Dil Desteği

### ISSUE THREAD

**Issue by AtakanCSKNDR** [devnotcom/devnot-mentor-front-end#8]
API endpointlerinden dönen [Hata mesajları](https://github.com/devnotcom/devnot-mentor-back-end/blob/master/Devnot.Mentor.Api/Common/ResultMessage.cs) için locales klasörü altındaki hata mesajlarına Türkçe ve İngilizce karşılıklarının yazılması ve çoklu dil desteğinin sağlanması gerekmektedir.

**Comment by umutluoglu** [comment]
Çoklu dil desteği ilk aşamada olmayacağı için bu issue'yu şimdilik kapatıyorum.
